// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// @umijs/renderer-*
export {
    createBrowserHistory,
    createHashHistory,
    createMemoryHistory,
    createSearchParams,
    matchPath,
    matchRoutes,
    Navigate,
    NavLink,
    Outlet,
    resolvePath,
    useLocation,
    useMatch,
    useNavigate,
    useOutlet,
    useOutletContext,
    useParams,
    useResolvedPath,
    useRoutes,
    useSearchParams,
    useAppData,
    useClientLoaderData,
    useServerLoaderData,
    renderClient,
    Link,
    useRouteData,
    __useFetcher
}
    from '/home/ryan/GolandProjects/test/go-easy-boot-web/node_modules/_@umijs_renderer-react@4.0.7@@umijs/renderer-react';
// umi/client/client/plugin
export {
    ApplyPluginsType, PluginManager
} from '/home/ryan/GolandProjects/test/go-easy-boot-web/node_modules/_umi@4.0.7@umi/client/client/plugin.js';
export {history, createHistory} from './core/history';
export {terminal} from './core/terminal';
// plugins
export {
    Access, useAccess, useAccessMarkedRoutes
} from '/home/ryan/GolandProjects/test/go-easy-boot-web/src/.umi/plugin-access';
export {
    addLocale,
    setLocale,
    getLocale,
    getIntl,
    useIntl,
    injectIntl,
    formatMessage,
    FormattedMessage,
    getAllLocales,
    SelectLang
} from '/home/ryan/GolandProjects/test/go-easy-boot-web/src/.umi/plugin-locale';
export {Provider, useModel} from '/home/ryan/GolandProjects/test/go-easy-boot-web/src/.umi/plugin-model';
export {
    useRequest, UseRequestProvider, request
} from '/home/ryan/GolandProjects/test/go-easy-boot-web/src/.umi/plugin-request';
// plugins types.d.ts
export * from '/home/ryan/GolandProjects/test/go-easy-boot-web/src/.umi/plugin-layout/types.d';
export * from '/home/ryan/GolandProjects/test/go-easy-boot-web/src/.umi/plugin-request/types.d';
