// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined
    from '/home/ryan/GolandProjects/test/go-easy-boot-web/node_modules/_@ant-design_icons@4.7.0@@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined
    from '/home/ryan/GolandProjects/test/go-easy-boot-web/node_modules/_@ant-design_icons@4.7.0@@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined
    from '/home/ryan/GolandProjects/test/go-easy-boot-web/node_modules/_@ant-design_icons@4.7.0@@ant-design/icons/es/icons/TableOutlined';

export default {SmileOutlined, CrownOutlined, TableOutlined};
