// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	captcha "system/api/internal/handler/captcha"
	menu "system/api/internal/handler/menu"
	role "system/api/internal/handler/role"
	system "system/api/internal/handler/system"
	user "system/api/internal/handler/user"
	"system/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Cros},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/system/health",
					Handler: system.HealthCheckHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Cros},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user/role",
					Handler: role.CreateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/user/role/:ID",
					Handler: role.UpdateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/user/role/:ID",
					Handler: role.DeleteRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/role/copy",
					Handler: role.CopyRoleHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Cros},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/menu",
					Handler: menu.CreateMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/menu/role",
					Handler: menu.AddRoleMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/menu/:id",
					Handler: menu.DeleteMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/menu/:id",
					Handler: menu.UpdateMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/menu",
					Handler: menu.GetMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/menu/list",
					Handler: menu.GetMenuListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/menu/tree",
					Handler: menu.GetMenuTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/menu/role/:ID",
					Handler: menu.GetRoleMenuHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Cros},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user/login",
					Handler: user.LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/register",
					Handler: user.RegisterHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Cros},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user/change-password",
					Handler: user.ChangePasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/info",
					Handler: user.GetUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/list",
					Handler: user.GetUserInfoListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/modify",
					Handler: user.ModifyInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/user/:id",
					Handler: user.DeleteUserInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Cros},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/captcha",
					Handler: captcha.GetCaptchaHandler(serverCtx),
				},
			}...,
		),
	)
}
